language: go
dist: focal

go: stable

git:
  submodules: true
  depth: 10

before_install:
  - python3 -m pip install meson ninja
  - curl -L https://github.com/dimkr/toolchains/releases/latest/download/arm-any32-linux-musleabi.tar.gz | sudo tar -xzvf - -C /
  - curl -L https://github.com/dimkr/toolchains/releases/latest/download/mips-any32-linux-musl.tar.gz | sudo tar -xzvf - -C /

script:
  - go test ./...
  - cd client
  - meson build && ninja -C build
  - meson --cross-file=arm-any32-linux-musleabi build-arm && ninja -C build-arm
  - meson --cross-file=mips-any32-linux-musl build-mips && ninja -C build-mips

addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - gcc
      - cmake
      - unzip

cache: ccache