language: go
dist: focal

go: stable

git:
  submodules: true
  depth: 10

env:
  - REDIS_URL=redis://localhost

install:
  - python3 -m pip install meson ninja
  - mkdir -p ~/toolchains
  - test -f ~/toolchains/arm-any32-linux-musleabi.tar.gz || curl -Lo ~/toolchains/arm-any32-linux-musleabi.tar.gz https://github.com/dimkr/toolchains/releases/latest/download/arm-any32-linux-musleabi.tar.gz
  - sudo tar -xzf ~/toolchains/arm-any32-linux-musleabi.tar.gz -C /
  - test -f ~/toolchains/mips-any32-linux-musl.tar.gz || curl -Lo ~/toolchains/mips-any32-linux-musl.tar.gz https://github.com/dimkr/toolchains/releases/latest/download/mips-any32-linux-musl.tar.gz
  - sudo tar -xzf ~/toolchains/mips-any32-linux-musl.tar.gz -C /
  - sudo service redis-server start

script:
  - go test ./...
  - ./ci/test_broker.sh
  - cd client
  - meson build & ninja -C build
  - meson --cross-file=arm-any32-linux-musleabi -Dssl_verify=false build-arm && ninja -C build-arm
  - meson --cross-file=mips-any32-linux-musl -Dssl_verify=false build-mips && ninja -C build-mips

addons:
  apt:
    packages:
      - redis-server
      - mosquitto-clients

cache:
  directories:
    - ~/.ccache
    - ~/.cache/go-build
    - ~/gopath/pkg/mod/cache
    - ~/toolchains
    - ~/.cache/pip