language: go
dist: focal

go: stable

git:
  submodules: true
  depth: 10

before_install:
  - python3 -m pip install meson ninja
  - curl -L https://github.com/dimkr/toolchains/releases/latest/download/arm-any32-linux-musleabi.tar.gz | sudo tar -xzf - -C /
  - curl -L https://github.com/dimkr/toolchains/releases/latest/download/mips-any32-linux-musl.tar.gz | sudo tar -xzf - -C /

script:
  - go test ./...
  - cd client
  - meson -Dssl=false build && ninja -C build
  - meson configure -Dssl=true build && ninja -C build
  - meson --cross-file=arm-any32-linux-musleabi -Dssl_verify=true build-arm && ninja -C build-arm
  - meson --cross-file=mips-any32-linux-musl -Dssl_verify=true build-mips && ninja -C build-mips

cache:
  directories:
    - ~/.ccache
    - ~/.cache/go-build
