language: go
dist: focal

go: stable

git:
  submodules: true
  depth: 10

services:
  - docker

env:
  - REDIS_URL=redis://localhost

before_install:
  - mkdir -p ~/dl
  - test -f ~/dl/arm-any32-linux-musleabi.tar.gz || curl -Lo ~/dl/arm-any32-linux-musleabi.tar.gz https://github.com/dimkr/toolchains/releases/latest/download/arm-any32-linux-musleabi.tar.gz
  - test -f ~/dl/mips-any32-linux-musl.tar.gz || curl -Lo ~/dl/mips-any32-linux-musl.tar.gz https://github.com/dimkr/toolchains/releases/latest/download/mips-any32-linux-musl.tar.gz
  - test -f ~/dl/minikube || curl -Lo ~/dl/minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64

install:
  - python3 -m pip install meson ninja
  - sudo tar -xzf ~/dl/arm-any32-linux-musleabi.tar.gz -C /
  - sudo tar -xzf ~/dl/mips-any32-linux-musl.tar.gz -C /
  - install -m 755 ~/dl/minikube ~/.local/bin/
  - echo -ne '#!/bin/sh\nexec minikube kubectl "$@"' > ~/.local/bin/kubectl
  - chmod 755 ~/.local/bin/kubectl

before_script:
  - minikube start --disk-size=2gb

script:
  - go test -timeout 10s ./...
  - cd client
  - meson -Db_sanitize=address build && meson test --print-errorlogs -C build
  - meson --cross-file=arm-any32-linux-musleabi -Dssl_verify=false build-arm && meson test --print-errorlogs -C build-arm
  - meson --cross-file=mips-any32-linux-musl -Dssl_verify=false build-mips && meson test --print-errorlogs -C build-mips
  - meson -Db_sanitize=address --optimization=3 -Dssl=false build-no-ssl && ninja -C build-no-ssl
  - cd ..
  - eval $(minikube -p minikube docker-env) && make -j`nproc`
  - eval $(minikube -p minikube docker-env) && make deploy
  - ./client/build-no-ssl/yodi -h `minikube ip` -p `kubectl get svc broker -o json | jq .spec.ports[0].nodePort` -i 0b8e29de-13a1-43cf-a793-4d898440550e -u user1 -P password1 &
  - (sleep 1 && mosquitto_pub -h `minikube ip` -p `kubectl get svc broker -o json | jq .spec.ports[0].nodePort` -u user3 -P password3 -t /0b8e29de-13a1-43cf-a793-4d898440550e/commands -f ci/command.json -q 1) &
  - mosquitto_sub -h `minikube ip` -p `kubectl get svc broker -o json | jq .spec.ports[0].nodePort` -u user2 -P password2 -t /0b8e29de-13a1-43cf-a793-4d898440550e/results -W 10 -C 1 > result
  - cmp result ci/result.json

addons:
  apt:
    packages:
      - mosquitto-clients
      - qemu-user-static

cache:
  directories:
    - ~/.ccache
    - ~/.cache/go-build
    - ~/gopath/pkg/mod/cache
    - ~/dl
    - ~/.cache/pip
    - ~/.minikube/cache