apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - env:
        - name: REDIS_URL
          value: redis://redis
        image: yodi/web
        imagePullPolicy: IfNotPresent
        name: web
        ports:
        - containerPort: 8080
          protocol: TCP
      initContainers:
        - name: busybox
          image: busybox
          command: ['sh', '-c', 'until nc -zw2 redis 6379; do sleep 1; done']