apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - env:
        - name: REDIS_URL
          value: redis://redis
        image: yodi/broker
        imagePullPolicy: IfNotPresent
        name: broker
        ports:
        - containerPort: 2883
          protocol: TCP
