apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailman
  labels:
    app: mailman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailman
  template:
    metadata:
      labels:
        app: mailman
    spec:
      containers:
      - env:
        - name: REDIS_URL
          value: redis://redis
        image: yodi/mailman
        imagePullPolicy: IfNotPresent
        name: mailman
