apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailman
  labels:
    app: mailman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailman
  template:
    metadata:
      labels:
        app: mailman
    spec:
      containers:
      - env:
        - name: REDIS_URL
          value: redis://redis
        image: yodi/mailman
        imagePullPolicy: IfNotPresent
        name: mailman
      initContainers:
        - name: busybox
          image: busybox
          command: ['sh', '-c', 'until nc -zw2 redis 6379; do sleep 1; done']