apiVersion: v1
kind: Service
metadata:
  labels:
    app: broker
  name: broker
  resourceVersion: "0"
spec:
  ports:
  - port: 1883
    protocol: TCP
    targetPort: 2883
  selector:
    app: broker
  type: NodePort
