apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-11T09:39:28Z"
  labels:
    app: broker
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":1883,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-07-11T09:39:28Z"
  name: broker
  namespace: default
  resourceVersion: "35545"
  selfLink: /api/v1/namespaces/default/services/broker
  uid: ce6f930a-97ad-4abf-b66f-125dd5b13b91
spec:
  ports:
  - port: 1883
    protocol: TCP
    targetPort: 2883
  selector:
    app: broker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
